In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('survey_results_public.csv')

In [3]:
df.describe()

Respondent           Age    CompenTotal     USDCompen   WorkWeekHrs
count  64461.000000  45446.000000   3.482600e+04  3.475600e+04  41151.000000
mean   32554.079738     30.834111  3.187274e+242  1.037561e+05     40.782174
std    18967.442360      9.585392            inf  2.268853e+05     17.816383
min        1.000000      1.000000   0.000000e+00  0.000000e+00      1.000000
25%    16116.000000     24.000000   2.000000e+04  2.464800e+04     40.000000
50%    32231.000000     29.000000   6.300000e+04  5.404900e+04     40.000000
75%    49142.000000     35.000000   1.250000e+05  9.500000e+04     44.000000
max    65639.000000    279.000000  1.110000e+247  2.000000e+06    475.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64461 entries, 0 to 64460
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Respondent                    64461 non-null  int64  
 1   MainBranch                    64162 non-null  object 
 2   Hobbyist                      64416 non-null  object 
 3   Age                           45446 non-null  float64
 4   Age1stCode                    57900 non-null  object 
 5   CompenFreq                    40069 non-null  object 
 6   CompenTotal                   34826 non-null  float64
 7   USDCompen                     34756 non-null  float64
 8   Country                       64072 non-null  object 
 9   CurrencyDesc                  45472 non-null  object 
 10  CurrencySymbol                45472 non-null  object 
 11  DatabaseDesireNextYear        44070 non-null  object 
 12  DatabaseWorkedWith            49537 non-null  object 
 13  D

In [5]:
df.head()

Respondent                                         MainBranch Hobbyist  \
0           1                     I am a developer by profession      Yes   
1           2                     I am a developer by profession       No   
2           3                        I code primarily as a hobby      Yes   
3           4                     I am a developer by profession      Yes   
4           5  I used to be a developer by profession, but no...      Yes   

    Age Age1stCode CompenFreq  CompenTotal  USDCompen             Country  \
0   NaN         13    Monthly          NaN        NaN             Germany   
1   NaN         19        NaN          NaN        NaN      United Kingdom   
2   NaN         15        NaN          NaN        NaN  Russian Federation   
3  25.0         18        NaN          NaN        NaN             Albania   
4  31.0         16        NaN          NaN        NaN       United States   

     CurrencyDesc  ...                  SurveyEase           SurveyLength  \
0   European Euro  ...  Neither easy nor difficult  Appropriate in length   
1  Pound sterling  ...                         NaN                    NaN   
2             NaN  ...  Neither easy nor difficult  Appropriate in length   
3    Albanian lek  ...                         NaN                    NaN   
4             NaN  ...                        Easy              Too short   

  Trans                                     UndergradMajor  \
0    No  Computer science, computer engineering, or sof...   
1   NaN  Computer science, computer engineering, or sof...   
2   NaN                                                NaN   
3    No  Computer science, computer engineering, or sof...   
4    No  Computer science, computer engineering, or sof...   

  WebframeDesireNextYear    WebframeWorkedWith  \
0           ASP.NET Core  ASP.NET;ASP.NET Core   
1                    NaN                   NaN   
2                    NaN                   NaN   
3                    NaN                   NaN   
4   Django;Ruby on Rails         Ruby on Rails   

                              WelcomeChange WorkWeekHrs YearsCode YearsCodePro  
0   Just as welcome now as I felt last year        50.0        36           27  
1  Somewhat more welcome now than last year         NaN         7            4  
2  Somewhat more welcome now than last year         NaN         4          NaN  
3  Somewhat less welcome now than last year        40.0         7            4  
4   Just as welcome now as I felt last year         NaN        15            8  

[5 rows x 61 columns]

In [6]:
#open schema in excel

In [7]:
def unq(i):
    print(df[i].value_counts())
    print('NaN','\t  ',df[i].isna().sum())
    print(df[i].unique())
def enc(i):
    df[i] = df[i].astype('category')
    df[i] = df[i].cat.codes 
def fna(a,b):
    df[a].fillna(b,inplace=True)
    unq(a)    

In [8]:
unq('MainBranch')

I am a developer by profession                                                   47193
I am a student who is learning to code                                            7970
I am not primarily a developer, but I write code sometimes as part of my work     5502
I code primarily as a hobby                                                       2314
I used to be a developer by profession, but no longer am                          1183
Name: MainBranch, dtype: int64
NaN 	   299
['I am a developer by profession' 'I code primarily as a hobby'
 'I used to be a developer by profession, but no longer am'
 'I am not primarily a developer, but I write code sometimes as part of my work'
 'I am a student who is learning to code' nan]


In [9]:
fna('MainBranch','I am a developer by profession')    

I am a developer by profession                                                   47492
I am a student who is learning to code                                            7970
I am not primarily a developer, but I write code sometimes as part of my work     5502
I code primarily as a hobby                                                       2314
I used to be a developer by profession, but no longer am                          1183
Name: MainBranch, dtype: int64
NaN 	   0
['I am a developer by profession' 'I code primarily as a hobby'
 'I used to be a developer by profession, but no longer am'
 'I am not primarily a developer, but I write code sometimes as part of my work'
 'I am a student who is learning to code']


In [54]:
enc('MainBranch')    
unq('MainBranch')

0    47492
1     7970
2     5502
3     2314
4     1183
Name: MainBranch, dtype: int64
NaN 	   0
[0 3 4 2 1]


In [11]:
unq('Hobbyist')

Yes    50388
No     14028
Name: Hobbyist, dtype: int64
NaN 	   45
['Yes' 'No' nan]


In [12]:
fna('Hobbyist','Yes')

Yes    50433
No     14028
Name: Hobbyist, dtype: int64
NaN 	   0
['Yes' 'No']


In [53]:
enc('Hobbyist')
unq('Hobbyist')

1    50433
0    14028
Name: Hobbyist, dtype: int64
NaN 	   0
[1 0]


In [14]:
unq('Age')

25.0    2693
28.0    2412
30.0    2406
26.0    2391
27.0    2338
        ... 
23.8       1
95.0       1
31.5       1
20.5       1
16.5       1
Name: Age, Length: 110, dtype: int64
NaN 	   19015
[  nan  25.   31.   36.   30.   22.   23.   49.   53.   27.   45.   32.
  24.   40.   18.   39.   29.   16.   34.   19.   35.   20.   38.   57.
  28.   17.   44.   21.   48.   26.   42.   55.   37.   50.   41.   64.
  63.   33.   43.   51.   60.   59.   62.   69.   52.   46.   49.5  56.
  47.   15.   72.   13.   71.   54.   70.   11.   14.   61.   26.8  86.
  58.   67.   94.   65.   66.   84.   73.   78.   68.   99.   74.   12.
  77.   15.5  85.   76.   35.7  32.5  81.   23.8  97.   96.   26.5   3.
  24.5  14.7  34.5   5.    1.   20.5  79.  279.   22.5  27.5  32.8  10.
  89.   80.   98.   19.8   7.   21.5  31.5  88.   39.5  16.5  75.   83.
  23.4  95.   14.5]


In [15]:
fna('Age',25.0)

25.0    21708
28.0     2412
30.0     2406
26.0     2391
27.0     2338
        ...  
23.8        1
95.0        1
31.5        1
20.5        1
16.5        1
Name: Age, Length: 110, dtype: int64
NaN 	   0
[ 25.   31.   36.   30.   22.   23.   49.   53.   27.   45.   32.   24.
  40.   18.   39.   29.   16.   34.   19.   35.   20.   38.   57.   28.
  17.   44.   21.   48.   26.   42.   55.   37.   50.   41.   64.   63.
  33.   43.   51.   60.   59.   62.   69.   52.   46.   49.5  56.   47.
  15.   72.   13.   71.   54.   70.   11.   14.   61.   26.8  86.   58.
  67.   94.   65.   66.   84.   73.   78.   68.   99.   74.   12.   77.
  15.5  85.   76.   35.7  32.5  81.   23.8  97.   96.   26.5   3.   24.5
  14.7  34.5   5.    1.   20.5  79.  279.   22.5  27.5  32.8  10.   89.
  80.   98.   19.8   7.   21.5  31.5  88.   39.5  16.5  75.   83.   23.4
  95.   14.5]


In [16]:
unq('Age1stCode')

15    5618
14    5514
16    5463
18    5382
12    5081
      ... 
63       1
83       1
76       1
68       1
72       1
Name: Age1stCode, Length: 63, dtype: int64
NaN 	   6561
['13' '19' '15' '18' '16' '14' '12' '20' '42' '8' '25' '22' '30' '17' '21'
 '10' '46' '9' '7' '11' '6' nan '31' '29' '5' 'Younger than 5 years' '28'
 '38' '23' '27' '41' '24' '53' '26' '35' '32' '40' '33' '36' '54' '48'
 '56' '45' '44' '34' 'Older than 85' '39' '51' '68' '50' '37' '47' '43'
 '52' '85' '64' '55' '58' '49' '76' '72' '73' '83' '63']


In [17]:
b = []
for i in df['Age1stCode']:
    b.append(i)
print(type(b)) 

<class 'list'>


In [28]:
for i in range(len(b)):
  if(b[i] == 'Older than 85'): 
    b[i] = 666
  elif(b[i] == 'Younger than 5 years'): 
    b[i] = 444
  else : 
    continue  

In [29]:
print(set(b))

{nan, '39', '26', '15', '44', 666, '11', '17', '12', '24', '52', '21', '68', '14', '85', '56', '64', '55', '53', '51', '10', '37', '5', '45', '73', '40', '54', '48', '25', 444, '35', '36', '41', '63', '76', '23', '32', '13', '8', '43', '58', '9', '6', '29', '38', '7', '46', '30', '20', '28', '19', '72', '83', '49', '42', '27', '18', '33', '16', '34', '22', '47', '31', '50'}


In [30]:
for i in range(len(b)):
    v = float(b[i]) 
    b[i] = v

In [31]:
print(set(b)) 

{nan, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 58.0, 444.0, 63.0, 64.0, 68.0, 72.0, 73.0, 76.0, 83.0, 85.0, 666.0}


In [32]:
df['Age1stCode_Modified']=b

In [33]:
df.drop(columns='Age1stCode',inplace=True)
df.head(3)

Respondent  MainBranch  Hobbyist   Age CompenFreq  CompenTotal  USDCompen  \
0           1           0         1  25.0    Monthly          NaN        NaN   
1           2           0         0  25.0        NaN          NaN        NaN   
2           3           3         1  25.0        NaN          NaN        NaN   

              Country    CurrencyDesc CurrencySymbol  ...  \
0             Germany   European Euro            EUR  ...   
1      United Kingdom  Pound sterling            GBP  ...   
2  Russian Federation             NaN            NaN  ...   

            SurveyLength Trans  \
0  Appropriate in length    No   
1                    NaN   NaN   
2  Appropriate in length   NaN   

                                      UndergradMajor WebframeDesireNextYear  \
0  Computer science, computer engineering, or sof...           ASP.NET Core   
1  Computer science, computer engineering, or sof...                    NaN   
2                                                NaN                    NaN   

     WebframeWorkedWith                             WelcomeChange WorkWeekHrs  \
0  ASP.NET;ASP.NET Core   Just as welcome now as I felt last year        50.0   
1                   NaN  Somewhat more welcome now than last year         NaN   
2                   NaN  Somewhat more welcome now than last year         NaN   

  YearsCode YearsCodePro Age1stCode_Modified  
0        36           27                10.0  
1         7            4                10.0  
2         4          NaN                11.0  

[3 rows x 61 columns]

In [34]:
df.rename(columns={'Age1stCode_Modified': 'Age1stCode'},inplace=True)
df.head(1)

Respondent  MainBranch  Hobbyist   Age CompenFreq  CompenTotal  USDCompen  \
0           1           0         1  25.0    Monthly          NaN        NaN   

   Country   CurrencyDesc CurrencySymbol  ...           SurveyLength Trans  \
0  Germany  European Euro            EUR  ...  Appropriate in length    No   

                                      UndergradMajor WebframeDesireNextYear  \
0  Computer science, computer engineering, or sof...           ASP.NET Core   

     WebframeWorkedWith                            WelcomeChange WorkWeekHrs  \
0  ASP.NET;ASP.NET Core  Just as welcome now as I felt last year        50.0   

  YearsCode YearsCodePro Age1stCode  
0        36           27       10.0  

[1 rows x 61 columns]

In [35]:
df['Age1stCode'].fillna(df['Age1stCode'].median,inplace=True)

In [36]:
unq('CompenFreq')

Yearly     19818
Monthly    18899
Weekly      1352
Name: CompenFreq, dtype: int64
NaN 	   24392
['Monthly' nan 'Yearly' 'Weekly']


In [37]:
fna('CompenFreq','Yearly')

Yearly     44210
Monthly    18899
Weekly      1352
Name: CompenFreq, dtype: int64
NaN 	   0
['Monthly' 'Yearly' 'Weekly']


In [52]:
enc('CompenFreq')
unq('CompenFreq')

2    44210
0    18899
1     1352
Name: CompenFreq, dtype: int64
NaN 	   0
[0 2 1]


In [39]:
unq('CompenTotal')

100000.0     769
60000.0      735
50000.0      717
120000.0     660
70000.0      617
            ... 
126700.0       1
17176.0        1
19410.0        1
2743900.0      1
49150.0        1
Name: CompenTotal, Length: 3003, dtype: int64
NaN 	   29635
[          nan 1.1600000e+05 2.5000000e+04 ... 1.2775000e+07 2.7170564e+07
 4.3100000e+06]


In [40]:
fna('CompenTotal',100000.0)

100000.0     30404
60000.0        735
50000.0        717
120000.0       660
70000.0        617
             ...  
126700.0         1
17176.0          1
19410.0          1
2743900.0        1
49150.0          1
Name: CompenTotal, Length: 3003, dtype: int64
NaN 	   0
[1.0000000e+05 1.1600000e+05 2.5000000e+04 ... 1.2775000e+07 2.7170564e+07
 4.3100000e+06]


In [41]:
unq('USDCompen')

120000.0     341
100000.0     306
150000.0     277
2000000.0    258
1000000.0    258
            ... 
102700.0       1
68721.0        1
96250.0        1
38456.0        1
21487.0        1
Name: USDCompen, Length: 6958, dtype: int64
NaN 	   29705
[    nan 116000.  32315. ...    369.    200.  38759.]


In [42]:
fna('USDCompen',120000.0)

120000.0     30046
100000.0       306
150000.0       277
2000000.0      258
1000000.0      258
             ...  
102700.0         1
68721.0          1
96250.0          1
38456.0          1
21487.0          1
Name: USDCompen, Length: 6958, dtype: int64
NaN 	   0
[120000. 116000.  32315. ...    369.    200.  38759.]


In [44]:
unq('Country')

United States     12469
India              8403
United Kingdom     3896
Germany            3890
Canada             2191
                  ...  
Gabon                 1
Saint Lucia           1
Chad                  1
Kiribati              1
Mali                  1
Name: Country, Length: 183, dtype: int64
NaN 	   389
['Germany' 'United Kingdom' 'Russian Federation' 'Albania' 'United States'
 'India' 'Tunisia' 'Spain' 'Netherlands' 'France' 'Belgium' 'Portugal'
 'Canada' 'China' 'Ukraine' 'Italy' 'Brazil' 'Austria' 'Mexico' 'Sweden'
 'Poland' 'Indonesia' 'Greece' 'Israel' 'Czech Republic'
 'Bosnia and Herzegovina' 'Bulgaria' 'Serbia' 'Switzerland' 'Hungary'
 'Nepal' 'Slovenia' 'Uruguay' 'Denmark' 'Pakistan' 'Taiwan' 'Romania'
 'Finland' 'Costa Rica' 'Nigeria' 'Chile' 'Turkey' 'Panama' 'Ireland'
 'Estonia' 'Philippines' 'Australia' 'Nomadic' 'Peru' 'Cyprus' 'Sri Lanka'
 'Kenya' 'Norway' 'Kyrgyzstan' 'Iran' 'Croatia' 'Egypt' 'Argentina'
 'Ghana' 'Latvia' 'Morocco' 'Bangladesh' 'Ecuador' 'Ha

In [45]:
fna('Country','United States')

United States     12858
India              8403
United Kingdom     3896
Germany            3890
Canada             2191
                  ...  
Gabon                 1
Saint Lucia           1
Chad                  1
Kiribati              1
Mali                  1
Name: Country, Length: 183, dtype: int64
NaN 	   0
['Germany' 'United Kingdom' 'Russian Federation' 'Albania' 'United States'
 'India' 'Tunisia' 'Spain' 'Netherlands' 'France' 'Belgium' 'Portugal'
 'Canada' 'China' 'Ukraine' 'Italy' 'Brazil' 'Austria' 'Mexico' 'Sweden'
 'Poland' 'Indonesia' 'Greece' 'Israel' 'Czech Republic'
 'Bosnia and Herzegovina' 'Bulgaria' 'Serbia' 'Switzerland' 'Hungary'
 'Nepal' 'Slovenia' 'Uruguay' 'Denmark' 'Pakistan' 'Taiwan' 'Romania'
 'Finland' 'Costa Rica' 'Nigeria' 'Chile' 'Turkey' 'Panama' 'Ireland'
 'Estonia' 'Philippines' 'Australia' 'Nomadic' 'Peru' 'Cyprus' 'Sri Lanka'
 'Kenya' 'Norway' 'Kyrgyzstan' 'Iran' 'Croatia' 'Egypt' 'Argentina'
 'Ghana' 'Latvia' 'Morocco' 'Bangladesh' 'Ecuador' 'Hait

In [51]:
enc('Country')
unq('Country')

175    12858
71      8403
173     3896
59      3890
30      2191
       ...  
102        1
122        1
91         1
32         1
106        1
Name: Country, Length: 183, dtype: int64
NaN 	   0
[ 59 173 137   1 175  71 167 153 116  55  16 132  30  34 171  78  23   9
 105 157 131  72  61  77  41  21  25 144 158  69 115 148 176  44 125 160
 136  54  37 120  33 168 126  75  51 130   8 121 129  40 154  83 123  87
  73  38  48   6  60  89 110  13  47  66 178  35  94  49  67  52  90 170
   2 179  63 159   0 147 172  15 155 151  81  58 174   5 142 117  86   7
 135  39  95 146  10  46  70  76 177 166 143   3 169  68  18  20 134  80
 101  74 152 128  98 162 112  82  28  79 118  99  43 127 124 163  97 133
  96  22   4 109 180 108  85 181 182  92 111 150  50 113 138  26  36 156
  19  29  12  42 145 165 119  14  17 140  88 161 104  64  24  11 103 139
  45 141  91 114  27  53  84  62  32 100  65 106  57 122  93 107 164 149
  31  56 102]


In [47]:
unq('CurrencySymbol')

USD    11050
EUR    10000
INR     4930
GBP     3127
CAD     1570
       ...  
KYD        1
LYD        1
MOP        1
LSL        1
FJD        1
Name: CurrencySymbol, Length: 141, dtype: int64
NaN 	   18989
['EUR' 'GBP' nan 'ALL' 'USD' 'INR' 'CAD' 'AUD' 'BRL' 'MXN' 'SEK' 'PLN'
 'IDR' 'ILS' 'CZK' 'BAM' 'BGN' 'UAH' 'CHF' 'HUF' 'NPR' 'UYU' 'PKR' 'NGN'
 'TRY' 'PHP' 'PEN' 'LKR' 'TWD' 'KGS' 'HRK' 'ARS' 'RUB' 'IRR' 'GHS' 'NOK'
 'MAD' 'RON' 'TND' 'HTG' 'COP' 'HNL' 'DKK' 'LBP' 'UGX' 'RSD' 'GTQ' 'SYP'
 'EGP' 'BDT' 'AED' 'ZAR' 'BYN' 'AOA' 'CLP' 'JOD' 'GEL' 'CRC' 'SAR' 'NZD'
 'AMD' 'MDL' 'CUP' 'SGD' 'VND' 'AZN' 'DOP' 'IMP' 'UZS' 'TTD' 'XOF' 'ISK'
 'KWD' 'TMT' 'KES' 'HKD' 'TZS' 'BOB' 'KRW' 'JPY' 'IQD' 'PYG' 'MYR' 'THB'
 'CNY' 'MMK' 'ZMW' 'KZT' 'KHR' 'MVR' 'CDF' 'MKD' 'MWK' 'QAR' 'BMD' 'DZD'
 'non' 'ANG' 'AFN' 'MNT' 'BWP' 'DJF' 'OMR' 'MRU' 'LYD' 'AWG' 'ETB' 'MGA'
 'NAD' 'RWF' 'SZL' 'BTN' 'XAF' 'BHD' 'YER' 'BBD' 'GIP' 'VES' 'JMD' 'NIO'
 'SLL' 'LAK' 'TJS' 'MUR' 'SOS' 'SDG' 'BND' 'XDR' 'KYD' 'GNF' 'FKP' 

In [48]:
fna('CurrencySymbol','USD')

USD    30039
EUR    10000
INR     4930
GBP     3127
CAD     1570
       ...  
KYD        1
LYD        1
MOP        1
LSL        1
FJD        1
Name: CurrencySymbol, Length: 141, dtype: int64
NaN 	   0
['EUR' 'GBP' 'USD' 'ALL' 'INR' 'CAD' 'AUD' 'BRL' 'MXN' 'SEK' 'PLN' 'IDR'
 'ILS' 'CZK' 'BAM' 'BGN' 'UAH' 'CHF' 'HUF' 'NPR' 'UYU' 'PKR' 'NGN' 'TRY'
 'PHP' 'PEN' 'LKR' 'TWD' 'KGS' 'HRK' 'ARS' 'RUB' 'IRR' 'GHS' 'NOK' 'MAD'
 'RON' 'TND' 'HTG' 'COP' 'HNL' 'DKK' 'LBP' 'UGX' 'RSD' 'GTQ' 'SYP' 'EGP'
 'BDT' 'AED' 'ZAR' 'BYN' 'AOA' 'CLP' 'JOD' 'GEL' 'CRC' 'SAR' 'NZD' 'AMD'
 'MDL' 'CUP' 'SGD' 'VND' 'AZN' 'DOP' 'IMP' 'UZS' 'TTD' 'XOF' 'ISK' 'KWD'
 'TMT' 'KES' 'HKD' 'TZS' 'BOB' 'KRW' 'JPY' 'IQD' 'PYG' 'MYR' 'THB' 'CNY'
 'MMK' 'ZMW' 'KZT' 'KHR' 'MVR' 'CDF' 'MKD' 'MWK' 'QAR' 'BMD' 'DZD' 'non'
 'ANG' 'AFN' 'MNT' 'BWP' 'DJF' 'OMR' 'MRU' 'LYD' 'AWG' 'ETB' 'MGA' 'NAD'
 'RWF' 'SZL' 'BTN' 'XAF' 'BHD' 'YER' 'BBD' 'GIP' 'VES' 'JMD' 'NIO' 'SLL'
 'LAK' 'TJS' 'MUR' 'SOS' 'SDG' 'BND' 'XDR' 'KYD' 'GNF' 'FKP' 'XPF' 'L

In [49]:
enc('CurrencySymbol')

In [50]:
unq('DatabaseDesireNextYear')

PostgreSQL                                                                                    2310
Microsoft SQL Server                                                                          1947
MySQL                                                                                         1823
MongoDB                                                                                       1624
SQLite                                                                                         966
                                                                                              ... 
DynamoDB;MongoDB;MySQL;Oracle;PostgreSQL                                                         1
DynamoDB;Elasticsearch;Firebase;MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;Redis;SQLite       1
MariaDB;Microsoft SQL Server;MongoDB;Oracle;PostgreSQL;Redis;SQLite                              1
Couchbase;Firebase;MariaDB;MongoDB;MySQL;SQLite                                                  1
DynamoDB;F

In [55]:
fna('DatabaseDesireNextYear','PostgreSQL')

PostgreSQL                                                                                    22701
Microsoft SQL Server                                                                           1947
MySQL                                                                                          1823
MongoDB                                                                                        1624
SQLite                                                                                          966
                                                                                              ...  
DynamoDB;MongoDB;MySQL;Oracle;PostgreSQL                                                          1
DynamoDB;Elasticsearch;Firebase;MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;Redis;SQLite        1
MariaDB;Microsoft SQL Server;MongoDB;Oracle;PostgreSQL;Redis;SQLite                               1
Couchbase;Firebase;MariaDB;MongoDB;MySQL;SQLite                                                   1


In [56]:
enc('DatabaseDesireNextYear')
unq('DatabaseDesireNextYear')

3186    22701
3068     1947
3162     1823
3130     1624
3192      966
        ...  
1395        1
1258        1
1290        1
1322        1
860         1
Name: DatabaseDesireNextYear, Length: 3193, dtype: int64
NaN 	   0
[3068 3186 3171 ... 2566 1202 2370]


In [58]:
unq('DatabaseWorkedWith')

MySQL                                                                           3827
Microsoft SQL Server                                                            3298
PostgreSQL                                                                      1937
SQLite                                                                          1313
Microsoft SQL Server;MySQL                                                      1158
                                                                                ... 
Couchbase;Elasticsearch;MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;SQLite       1
Cassandra;Elasticsearch;Firebase;Microsoft SQL Server;PostgreSQL;Redis             1
Cassandra;MariaDB;Microsoft SQL Server;MySQL;Redis;SQLite                          1
Cassandra;DynamoDB;MariaDB;MongoDB;MySQL;PostgreSQL;Redis                          1
Couchbase;DynamoDB;MariaDB;MySQL;PostgreSQL;Redis;SQLite                           1
Name: DatabaseWorkedWith, Length: 2808, dtype: int64
NaN 	   1492

In [60]:
fna('DatabaseWorkedWith','MySQL')
enc('DatabaseWorkedWith')
unq('DatabaseWorkedWith')
def proc(a,b):
    fna(a,b)
    enc(a)
    unq(a)

2777    18751
2683     3298
2801     1937
2807     1313
2714     1158
        ...  
1003        1
1067        1
1099        1
2487        1
1225        1
Name: DatabaseWorkedWith, Length: 2808, dtype: int64
NaN 	   0
[2085 2777 2788 ...   45   37 2169]
2777    18751
2683     3298
2801     1937
2807     1313
2714     1158
        ...  
1003        1
1067        1
1099        1
2487        1
1225        1
Name: DatabaseWorkedWith, Length: 2808, dtype: int64
NaN 	   0
[2085 2777 2788 ...   45   37 2169]


In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64461 entries, 0 to 64460
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Respondent                    64461 non-null  int64  
 1   MainBranch                    64461 non-null  int8   
 2   Hobbyist                      64461 non-null  int8   
 3   Age                           64461 non-null  float64
 4   CompenFreq                    64461 non-null  int8   
 5   CompenTotal                   64461 non-null  float64
 6   USDCompen                     64461 non-null  float64
 7   Country                       64461 non-null  int16  
 8   CurrencyDesc                  45472 non-null  object 
 9   CurrencySymbol                64461 non-null  int16  
 10  DatabaseDesireNextYear        64461 non-null  int16  
 11  DatabaseWorkedWith            49537 non-null  object 
 12  DevType                       49370 non-null  object 
 13  E

In [61]:
unq('DevType')

Developer, full-stack                                                                                                                                                                                                                                                                                                                                                                                        4424
Developer, back-end                                                                                                                                                                                                                                                                                                                                                                                          3086
Developer, back-end;Developer, front-end;Developer, full-stack                                                                                                                                      

In [65]:
df.DevType.head()

0    Developer, desktop or enterprise applications;...
1              Developer, full-stack;Developer, mobile
2                                                  NaN
3                                                  NaN
4                                                  NaN
Name: DevType, dtype: object